version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: 'astro'
        update-types: ['version-update:semver-major']
      - dependency-name: '@astrojs/cloudflare'
        update-types: ['version-update:semver-major']
      - dependency-name: '@astrojs/markdoc'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
